import { ToolCategory, ToolCategoryFilter, ToolDefinition } from "@/lib/types";

export const categoryFilters: ToolCategoryFilter[] = ["All", "Image", "PDF", "Text", "Utility"];

export const toolCategories: ToolCategory[] = ["Image", "PDF", "Text", "Utility"];

export const liveToolSlugs = new Set([
  "advanced-pdf-editor",
  "pdf-editor",
  "word-counter",
  "case-converter",
  "json-formatter",
  "password-generator",
  "uuid-generator",
  "qr-code-generator",
  "image-compressor",
  "image-resizer",
  "png-to-jpg-converter",
  "image-to-text-ocr",
  "image-text-editor",
  "pdf-merge",
  "pdf-split",
  "pdf-compressor",
]);

export const tools: ToolDefinition[] = [
  {
    name: "Image Compressor",
    slug: "image-compressor",
    description: "Compress images in seconds while preserving visual quality.",
    category: "Image",
    icon: "compress",
    aiContext: "Image compression and export quality tuning",
  },
  {
    name: "Image Resizer",
    slug: "image-resizer",
    description: "Resize images for social posts, websites, and documents.",
    category: "Image",
    icon: "resize",
    aiContext: "Image resizing for social, web, and print use cases",
  },
  {
    name: "Image to Text (OCR)",
    slug: "image-to-text-ocr",
    description: "Extract editable text from photos and scanned documents.",
    category: "Image",
    icon: "scan",
    aiContext: "OCR extraction, cleanup, and post-processing guidance",
  },
  {
    name: "PNG to JPG Converter",
    slug: "png-to-jpg-converter",
    description: "Convert transparent PNG files to clean JPG outputs instantly.",
    category: "Image",
    icon: "convert",
    aiContext: "PNG to JPG conversion and background handling",
  },
  {
    name: "Image Text Editor",
    slug: "image-text-editor",
    description: "Edit text detected from images with AI-ready OCR controls.",
    category: "Image",
    icon: "textImage",
    isPopular: true,
    aiContext: "Image text editing and OCR-assisted correction",
  },
  {
    name: "PDF Editor",
    slug: "pdf-editor",
    description: "Add, remove, highlight, and annotate PDF content in one place.",
    category: "PDF",
    icon: "pdfEdit",
    isPopular: true,
    aiContext: "PDF editing, annotation placement, and export troubleshooting",
  },
  {
    name: "Advanced PDF Editor",
    slug: "advanced-pdf-editor",
    description: "Compress and optimize PDFs using open-source Ghostscript engine.",
    category: "PDF",
    icon: "pdfEdit",
    aiContext: "PDF compression, optimization, and file size reduction",
  },
  {
    name: "PDF Merge",
    slug: "pdf-merge",
    description: "Combine multiple PDFs into one polished file.",
    category: "PDF",
    icon: "merge",
    aiContext: "PDF merge ordering and final document structure",
  },
  {
    name: "PDF Split",
    slug: "pdf-split",
    description: "Split long PDF files into focused pages in a click.",
    category: "PDF",
    icon: "split",
    aiContext: "PDF splitting strategies by ranges and document sections",
  },
  {
    name: "PDF Compressor",
    slug: "pdf-compressor",
    description: "Reduce large PDF sizes for easy sharing and uploads.",
    category: "PDF",
    icon: "compress",
    aiContext: "PDF compression tradeoffs between size and readability",
  },
  {
    name: "Word Counter",
    slug: "word-counter",
    description: "Count words, sentences, and reading time instantly.",
    category: "Text",
    icon: "word",
    aiContext: "Word count analysis, readability, and writing targets",
  },
  {
    name: "Case Converter",
    slug: "case-converter",
    description: "Switch text between uppercase, lowercase, and title case.",
    category: "Text",
    icon: "case",
    aiContext: "Text casing standards and formatting consistency",
  },
  {
    name: "JSON Formatter",
    slug: "json-formatter",
    description: "Beautify and validate JSON payloads with one click.",
    category: "Text",
    icon: "json",
    aiContext: "JSON formatting, validation, and schema-friendly structure",
  },
  {
    name: "Password Generator",
    slug: "password-generator",
    description: "Create secure, random passwords tailored to your rules.",
    category: "Text",
    icon: "password",
    aiContext: "Password strength guidance and secure credential practices",
  },
  {
    name: "UUID Generator",
    slug: "uuid-generator",
    description: "Generate versioned UUIDs for reliable unique identifiers.",
    category: "Text",
    icon: "uuid",
    aiContext: "UUID usage guidance across APIs and data systems",
  },
  {
    name: "QR Code Generator",
    slug: "qr-code-generator",
    description: "Create scannable QR codes for links, text, and contact details.",
    category: "Utility",
    icon: "qr",
    aiContext: "QR code content strategy, size, and scan reliability",
  },
];

export const popularTools = tools.filter((tool) => tool.isPopular);
